import {
  fontSize,
  fontFamily,
  fontWeightBold,
  fontWeightLight,
  fontWeightRegular,
} from '../settings';

import text from '../palette/text';
import { pxToRem } from '../utils';

const typographyOptions = {
  fontSize,
  fontFamily,
  fontWeightLight,
  fontWeightRegular,
  fontWeightMedium: fontWeightBold,
  h1: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(104),
    lineHeight: 'normal',
  },
  h2: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(65.5),
    lineHeight: 'normal',
    letterSpacing: '-0.03px',
  },
  h3: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(52.1),
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  h4: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(36.9),
    lineHeight: 'normal',
    letterSpacing: '0.01px',
  },
  h5: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(26),
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  h6: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(21.7),
    lineHeight: 'normal',
    letterSpacing: '0.01px',
  },
  subtitle1: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(13),
    lineHeight: 1.38,
    letterSpacing: '0.01px',
  },
  subtitle2: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(12),
    lineHeight: 1.58,
    letterSpacing: '0px',
  },
  body1: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(17.4),
    lineHeight: 1.61,
    letterSpacing: '0px',
  },
  body2: {
    color: text.primary,
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: pxToRem(15.2),
    lineHeight: 1.32,
    letterSpacing: '0px',
  },
  button: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(15.2),
    lineHeight: 1.23,
    letterSpacing: 'normal',
    textTransform: 'none',
  },
  caption: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(13),
    lineHeight: 1.23,
    letterSpacing: '0.4px',
    textTransform: 'none',
  },
  overline: {
    color: text.primary,
    fontWeight: fontWeightRegular,
    fontStyle: 'normal',
    fontSize: pxToRem(13),
    lineHeight: 1.15,
    letterSpacing: '0.03px',
  },
};

export default typographyOptions;
