name: Build-Pack-Release
on:
  push:
    branches:
      - master
jobs:
  build_pack_release:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FA_NPM_TOKEN: ${{secrets.FA_NPM_TOKEN}}
      CSC_LINK: ${{secrets.CSC_LINK}}
      CSC_KEY_PASSWORD: ${{secrets.CSC_KEY_PASSWORD}}
      CSC_IDENTITY_AUTO_DISCOVERY: ${{secrets.CSC_IDENTITY_AUTO_DISCOVERY}}
      WIN_CSC_IDENTITY_AUTO_DISCOVERY: ${{secrets.WIN_CSC_IDENTITY_AUTO_DISCOVERY}}
      APPLE_ID: ${{secrets.APPLE_ID}}
      APPLE_PASSWORD: ${{secrets.APPLE_PASSWORD}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install --network-timeout 1000000
      - name: Linux app pack and release
        if: matrix.os == 'ubuntu-latest'
        run: yarn electron-pack --linux
      - name: MacOS app pack and release
        if: matrix.os == 'macos-latest'
        run: yarn electron-pack --mac
      - name: Windows app pack and release
        if: matrix.os == 'windows-latest'
        run: yarn electron-pack --win --x64 --ia32